#!/usr/bin/env bash
# Dumps the Sail model's signature region for a test, in the same format
# spike_sig.sh produces, so compare.py can diff either reference against
# DoomV without knowing which one it is looking at.
#
# Sail is the formal RISC-V specification -- the model is generated from the
# same source the architecture is defined in, rather than being an
# independent reimplementation. Where it and spike disagree, Sail is the
# stronger authority. It is also the only one of the two with RVA23
# profile configurations.
#
# The config is generated by tools/verification/simulators/sail/mkconfig.py
# from the profile's own extension list rather than taken from
# riscv-arch-test's config/sail/sail-RVA23S64. That config requires platform
# properties which postdate it and cannot be loaded by any tagged Sail
# release; it appears to track an untagged revision. Since the yaml's
# extension list is the authoritative content and the json is one
# serialisation of it, generating from the list is both more robust and
# closer to the source of truth.
#
# Note the config is RVA23-or-better: Sail's defaults enable extensions
# beyond the mandatory set. That is harmless for use as an oracle -- a
# superset model still answers correctly for the subset under test -- but it
# is not by itself evidence that DoomV's extension set matches the profile.
# The static audit in mkconfig.py establishes that separately.
set -euo pipefail

TEST="${1:-vtest_v}"
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

ROOT="$(cd "$DIR/../../../../.." && pwd)"
MANIFEST="$ROOT/build/verification/tools.json"
if [ -z "${SAIL:-}" ] && [ -f "$MANIFEST" ]; then
    SAIL="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["sail"])' "$MANIFEST")"
fi
SAIL="${SAIL:-$ROOT/tools/verification/simulators/sail/src/build/c_emulator/sail_riscv_sim}"
CONFIG="${SAIL_CONFIG:-$ROOT/tools/verification/simulators/sail/rva23s64.json}"
NM=riscv64-linux-gnu-nm

[ -x "$SAIL" ] || { echo "ERROR: sail_riscv_sim not built at $SAIL" >&2; exit 1; }
[ -f "$TEST.elf" ] || { echo "ERROR: $TEST.elf not built -- run build_elf.sh first" >&2; exit 1; }

sym() { $NM "$TEST.elf" | awk -v s="$1" '$3==s {print $1}'; }
BEG=$(sym begin_signature)
END=$(sym end_signature)
echo "$TEST: sail begin=0x$BEG end=0x$END" >&2

# Sail has a purpose-built --test-signature option that writes the region
# between begin_signature and end_signature directly, one 32-bit word per
# line -- the same shape spike_sig.sh produces. An earlier version of this
# script dumped memory and sliced it by hand, which silently produced zero
# words because it guessed the dump file naming wrong.
#
# The instruction limit is generous: these tests are short, and the limit
# exists to bound a runaway rather than to be reached.
rm -f "$TEST.sail.sig"
RAW="$(mktemp)"
trap 'rm -f "$RAW"' EXIT
if ! timeout 300 "$SAIL" --config "$CONFIG" --test-signature "$TEST.sail.sig" \
    --inst-limit 5000000 "./$TEST.elf" > "$RAW" 2>&1; then
    cat "$RAW" >&2
    exit 1
fi

if ! grep -q "SUCCESS" "$RAW" || [ ! -s "$TEST.sail.sig" ]; then
	echo "ERROR: sail did not reach the test's HTIF exit:" >&2
	tail -4 "$RAW" >&2
	# A common cause is a test that drops to S-mode without installing a
	# PMP entry: with PMP implemented and nothing configured, the spec
	# denies S and U access outright, and the test faults before its first
	# instruction there. Every suite here that drops privilege sets up a
	# permit-all entry for that reason.
	exit 1
fi

echo "$TEST.sail.sig words: $(wc -l < "$TEST.sail.sig")" >&2
